### PR TITLE
Create Hebrew translation

### PR DESCRIPTION
**Pull request by Eng2Heb**

### CODE REVIEW

**Comment by Connum** [comment]
Hi there and thanks for your contribution!
There's just an issue: Integration of "TV Show - next Aired" hast been removed in the latest release because it was against Kodi's regulation of not changing the settings of another Add-On. Please update your fork to the current revision and remove the language strings that are no longer needed.

Thanks!

**Comment by Eng2Heb** [comment]
Hi,

Can you please give me a link to the current revision and I'll do the rest?

Thank you in advanced.



2017-10-09 13:39 GMT+03:00 Connum <notifications@github.com>:

**Comment by Connum** [comment]
Hi,
just pull the current state of my repo: https://github.com/Connum/script.myepisodecalendar

**Comment by Eng2Heb** [comment]
Hi,
It look like its up to date. as in your current English strings.
Pls re-check




2017-10-09 14:41 GMT+03:00 Connum <notifications@github.com>:

**Comment by Connum** [comment]
Ohhh, you are right! I forgot to remove some of the now unneeded strings. I'll merge your pull request and remove those strings in the English and Hebrew files before the next release.

Thanks again!

**Pull request merged**
